# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfazMenu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1063, 731)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1351, 681))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(340, 30, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.TabP1 = QtGui.QWidget()
        self.TabP1.setObjectName(_fromUtf8("TabP1"))
        self.buttonSeleccionarExcel = QtGui.QPushButton(self.TabP1)
        self.buttonSeleccionarExcel.setGeometry(QtCore.QRect(460, 490, 191, 121))
        self.buttonSeleccionarExcel.setObjectName(_fromUtf8("buttonSeleccionarExcel"))
        self.label = QtGui.QLabel(self.TabP1)
        self.label.setGeometry(QtCore.QRect(470, 0, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.TabP1)
        self.label_5.setGeometry(QtCore.QRect(180, 190, 361, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.TabP1)
        self.label_6.setGeometry(QtCore.QRect(240, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.TabP1)
        self.label_7.setGeometry(QtCore.QRect(140, 230, 421, 51))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.TabP1)
        self.label_8.setGeometry(QtCore.QRect(100, 280, 591, 51))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.TabP1)
        self.label_9.setGeometry(QtCore.QRect(800, 130, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.TabP1)
        self.label_10.setGeometry(QtCore.QRect(740, 190, 321, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.TabP1)
        self.label_11.setGeometry(QtCore.QRect(630, 230, 561, 51))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.TabP1)
        self.label_12.setGeometry(QtCore.QRect(710, 290, 401, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.TabP1, _fromUtf8(""))
        self.TabP2 = QtGui.QWidget()
        self.TabP2.setObjectName(_fromUtf8("TabP2"))
        self.label_2 = QtGui.QLabel(self.TabP2)
        self.label_2.setGeometry(QtCore.QRect(470, 0, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.buttonCalcularCarretera = QtGui.QPushButton(self.TabP2)
        self.buttonCalcularCarretera.setGeometry(QtCore.QRect(530, 600, 171, 41))
        self.buttonCalcularCarretera.setObjectName(_fromUtf8("buttonCalcularCarretera"))
        self.nombreCantidadCarreteras = QtGui.QLabel(self.TabP2)
        self.nombreCantidadCarreteras.setGeometry(QtCore.QRect(40, 90, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras.setFont(font)
        self.nombreCantidadCarreteras.setObjectName(_fromUtf8("nombreCantidadCarreteras"))
        self.spinBoxCantCarreteras = QtGui.QSpinBox(self.TabP2)
        self.spinBoxCantCarreteras.setEnabled(True)
        self.spinBoxCantCarreteras.setGeometry(QtCore.QRect(400, 90, 51, 41))
        self.spinBoxCantCarreteras.setMinimum(1)
        self.spinBoxCantCarreteras.setMaximum(8)
        self.spinBoxCantCarreteras.setObjectName(_fromUtf8("spinBoxCantCarreteras"))
        self.tableWidgetRutas = QtGui.QTableWidget(self.TabP2)
        self.tableWidgetRutas.setGeometry(QtCore.QRect(70, 170, 631, 192))
        self.tableWidgetRutas.setAlternatingRowColors(True)
        self.tableWidgetRutas.setObjectName(_fromUtf8("tableWidgetRutas"))
        self.tableWidgetRutas.setColumnCount(5)
        self.tableWidgetRutas.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRutas.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRutas.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRutas.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRutas.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRutas.setHorizontalHeaderItem(4, item)
        self.nombreCantidadCarreteras_2 = QtGui.QLabel(self.TabP2)
        self.nombreCantidadCarreteras_2.setGeometry(QtCore.QRect(40, 140, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_2.setFont(font)
        self.nombreCantidadCarreteras_2.setObjectName(_fromUtf8("nombreCantidadCarreteras_2"))
        self.nombreCantidadCarreteras_3 = QtGui.QLabel(self.TabP2)
        self.nombreCantidadCarreteras_3.setGeometry(QtCore.QRect(40, 370, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_3.setFont(font)
        self.nombreCantidadCarreteras_3.setObjectName(_fromUtf8("nombreCantidadCarreteras_3"))
        self.gridLayoutWidget = QtGui.QWidget(self.TabP2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 410, 641, 163))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutVariables = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutVariables.setObjectName(_fromUtf8("gridLayoutVariables"))
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayoutVariables.addWidget(self.label_14, 5, 0, 1, 1)
        self.doubleSpinBoxTC2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxTC2.setDecimals(3)
        self.doubleSpinBoxTC2.setMaximum(9999.999)
        self.doubleSpinBoxTC2.setObjectName(_fromUtf8("doubleSpinBoxTC2"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxTC2, 5, 4, 1, 1)
        self.labelCondicion = QtGui.QLabel(self.gridLayoutWidget)
        self.labelCondicion.setObjectName(_fromUtf8("labelCondicion"))
        self.gridLayoutVariables.addWidget(self.labelCondicion, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.doubleSpinBoxTC1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxTC1.setDecimals(3)
        self.doubleSpinBoxTC1.setMaximum(9999.999)
        self.doubleSpinBoxTC1.setObjectName(_fromUtf8("doubleSpinBoxTC1"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxTC1, 5, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayoutVariables.addWidget(self.label_18, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.labelLCondicion2 = QtGui.QLabel(self.gridLayoutWidget)
        self.labelLCondicion2.setObjectName(_fromUtf8("labelLCondicion2"))
        self.gridLayoutVariables.addWidget(self.labelLCondicion2, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayoutVariables.addWidget(self.label_15, 4, 0, 1, 1)
        self.doubleSpinBoxCosC2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxCosC2.setDecimals(3)
        self.doubleSpinBoxCosC2.setMaximum(9999.999)
        self.doubleSpinBoxCosC2.setObjectName(_fromUtf8("doubleSpinBoxCosC2"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxCosC2, 4, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayoutVariables.addWidget(self.label_13, 3, 0, 1, 1)
        self.doubleSpinBoxPC2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxPC2.setDecimals(3)
        self.doubleSpinBoxPC2.setMaximum(9999.999)
        self.doubleSpinBoxPC2.setObjectName(_fromUtf8("doubleSpinBoxPC2"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxPC2, 6, 4, 1, 1)
        self.doubleSpinBoxLC1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxLC1.setEnabled(True)
        self.doubleSpinBoxLC1.setDecimals(3)
        self.doubleSpinBoxLC1.setMaximum(9999.999)
        self.doubleSpinBoxLC1.setObjectName(_fromUtf8("doubleSpinBoxLC1"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxLC1, 3, 2, 1, 1)
        self.doubleSpinBoxCosC1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxCosC1.setDecimals(3)
        self.doubleSpinBoxCosC1.setMaximum(9999.999)
        self.doubleSpinBoxCosC1.setObjectName(_fromUtf8("doubleSpinBoxCosC1"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxCosC1, 4, 2, 1, 1)
        self.doubleSpinBoxPC1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxPC1.setDecimals(3)
        self.doubleSpinBoxPC1.setMaximum(9999.999)
        self.doubleSpinBoxPC1.setObjectName(_fromUtf8("doubleSpinBoxPC1"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxPC1, 6, 2, 1, 1)
        self.doubleSpinBoxLC2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxLC2.setDecimals(3)
        self.doubleSpinBoxLC2.setMaximum(9999.999)
        self.doubleSpinBoxLC2.setObjectName(_fromUtf8("doubleSpinBoxLC2"))
        self.gridLayoutVariables.addWidget(self.doubleSpinBoxLC2, 3, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayoutVariables.addWidget(self.label_16, 6, 0, 1, 1)
        self.labelComparacion = QtGui.QLabel(self.gridLayoutWidget)
        self.labelComparacion.setObjectName(_fromUtf8("labelComparacion"))
        self.gridLayoutVariables.addWidget(self.labelComparacion, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBoxL = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxL.setObjectName(_fromUtf8("comboBoxL"))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.comboBoxL.addItem(_fromUtf8(""))
        self.gridLayoutVariables.addWidget(self.comboBoxL, 3, 1, 1, 1)
        self.comboBoxCos = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxCos.setObjectName(_fromUtf8("comboBoxCos"))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.comboBoxCos.addItem(_fromUtf8(""))
        self.gridLayoutVariables.addWidget(self.comboBoxCos, 4, 1, 1, 1)
        self.comboBoxT = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxT.setObjectName(_fromUtf8("comboBoxT"))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.comboBoxT.addItem(_fromUtf8(""))
        self.gridLayoutVariables.addWidget(self.comboBoxT, 5, 1, 1, 1)
        self.comboBoxP = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxP.setObjectName(_fromUtf8("comboBoxP"))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.comboBoxP.addItem(_fromUtf8(""))
        self.gridLayoutVariables.addWidget(self.comboBoxP, 6, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.TabP2)
        self.scrollArea.setGeometry(QtCore.QRect(730, 200, 301, 321))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 319))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.nombreCantidadCarreteras_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.nombreCantidadCarreteras_4.setGeometry(QtCore.QRect(100, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_4.setFont(font)
        self.nombreCantidadCarreteras_4.setObjectName(_fromUtf8("nombreCantidadCarreteras_4"))
        self.labelResultados = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelResultados.setGeometry(QtCore.QRect(10, 50, 281, 231))
        self.labelResultados.setText(_fromUtf8(""))
        self.labelResultados.setObjectName(_fromUtf8("labelResultados"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.TabP2, _fromUtf8(""))
        self.TapP3 = QtGui.QWidget()
        self.TapP3.setObjectName(_fromUtf8("TapP3"))
        self.label_3 = QtGui.QLabel(self.TapP3)
        self.label_3.setGeometry(QtCore.QRect(470, 0, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.spinBoxOrden = QtGui.QSpinBox(self.TapP3)
        self.spinBoxOrden.setEnabled(True)
        self.spinBoxOrden.setGeometry(QtCore.QRect(430, 90, 51, 41))
        self.spinBoxOrden.setMinimum(1)
        self.spinBoxOrden.setMaximum(8)
        self.spinBoxOrden.setObjectName(_fromUtf8("spinBoxOrden"))
        self.nombreOrdenEstructura = QtGui.QLabel(self.TapP3)
        self.nombreOrdenEstructura.setGeometry(QtCore.QRect(70, 90, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreOrdenEstructura.setFont(font)
        self.nombreOrdenEstructura.setObjectName(_fromUtf8("nombreOrdenEstructura"))
        self.nombreDatosEstructura = QtGui.QLabel(self.TapP3)
        self.nombreDatosEstructura.setGeometry(QtCore.QRect(70, 140, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreDatosEstructura.setFont(font)
        self.nombreDatosEstructura.setObjectName(_fromUtf8("nombreDatosEstructura"))
        self.tableWidgetDatosEstructura = QtGui.QTableWidget(self.TapP3)
        self.tableWidgetDatosEstructura.setGeometry(QtCore.QRect(260, 170, 631, 192))
        self.tableWidgetDatosEstructura.setAlternatingRowColors(True)
        self.tableWidgetDatosEstructura.setObjectName(_fromUtf8("tableWidgetDatosEstructura"))
        self.tableWidgetDatosEstructura.setColumnCount(1)
        self.tableWidgetDatosEstructura.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDatosEstructura.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDatosEstructura.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDatosEstructura.setItem(0, 0, item)
        self.pushButtonEvaluarEstructura = QtGui.QPushButton(self.TapP3)
        self.pushButtonEvaluarEstructura.setGeometry(QtCore.QRect(510, 380, 131, 23))
        self.pushButtonEvaluarEstructura.setObjectName(_fromUtf8("pushButtonEvaluarEstructura"))
        self.scrollArea_2 = QtGui.QScrollArea(self.TapP3)
        self.scrollArea_2.setGeometry(QtCore.QRect(50, 420, 841, 201))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 839, 199))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.nombreCantidadCarreteras_5 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.nombreCantidadCarreteras_5.setGeometry(QtCore.QRect(470, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_5.setFont(font)
        self.nombreCantidadCarreteras_5.setObjectName(_fromUtf8("nombreCantidadCarreteras_5"))
        self.labelResultadosPrograma3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.labelResultadosPrograma3.setGeometry(QtCore.QRect(10, 50, 811, 111))
        self.labelResultadosPrograma3.setText(_fromUtf8(""))
        self.labelResultadosPrograma3.setObjectName(_fromUtf8("labelResultadosPrograma3"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.TapP3, _fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(500, 710, 72, 20))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Proyecto Álgebra Lineal", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "About", None))
        self.buttonSeleccionarExcel.setText(_translate("MainWindow", "Seleccionar excel", None))
        self.label.setText(_translate("MainWindow", "Programa 1", None))
        self.label_5.setText(_translate("MainWindow", "El Programa lee y retorna un archivo de excel", None))
        self.label_6.setText(_translate("MainWindow", "Importante", None))
        self.label_7.setText(_translate("MainWindow", "El Excel de entrada puede estar en cualquier ubicación", None))
        self.label_8.setText(_translate("MainWindow", "El Excel de salida (Resultado.xlsx) se guarda en la ubicación del programa", None))
        self.label_9.setText(_translate("MainWindow", "Instrucciones", None))
        self.label_10.setText(_translate("MainWindow", "1. Seleccione el libro de Excel con los datos", None))
        self.label_11.setText(_translate("MainWindow", "(El Programa hará los calculos y generará el resultado automáticamente)", None))
        self.label_12.setText(_translate("MainWindow", "2. Abra el Excel Resultado.xlsx, y observe los datos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabP1), _translate("MainWindow", "Programa 1", None))
        self.label_2.setText(_translate("MainWindow", "Programa 2", None))
        self.buttonCalcularCarretera.setText(_translate("MainWindow", "Calcular", None))
        self.nombreCantidadCarreteras.setText(_translate("MainWindow", "1. Digite la Cantidad de Carreteras (1-8):", None))
        item = self.tableWidgetRutas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ruta", None))
        item = self.tableWidgetRutas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Longitud (Kms)", None))
        item = self.tableWidgetRutas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Costo (Millones de dólares)", None))
        item = self.tableWidgetRutas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tiempo de Construccion (Meses)", None))
        item = self.tableWidgetRutas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Población Beneficiada (Miles de personas)", None))
        self.nombreCantidadCarreteras_2.setText(_translate("MainWindow", "2. Introduzca los datos para cada ruta:", None))
        self.nombreCantidadCarreteras_3.setText(_translate("MainWindow", "3. Introduzca los parámetros para las condiciones:", None))
        self.label_14.setText(_translate("MainWindow", "Tiempo Total", None))
        self.labelCondicion.setText(_translate("MainWindow", "Condición 1", None))
        self.label_18.setText(_translate("MainWindow", "Variables", None))
        self.labelLCondicion2.setText(_translate("MainWindow", "Condición 2", None))
        self.label_15.setText(_translate("MainWindow", "Costo Total", None))
        self.label_13.setText(_translate("MainWindow", "Longitud Total", None))
        self.label_16.setText(_translate("MainWindow", "Poblacion Beneficiada", None))
        self.labelComparacion.setText(_translate("MainWindow", "Comparación", None))
        self.comboBoxL.setItemText(0, _translate("MainWindow", "L > C", None))
        self.comboBoxL.setItemText(1, _translate("MainWindow", "L >= C", None))
        self.comboBoxL.setItemText(2, _translate("MainWindow", "L < C", None))
        self.comboBoxL.setItemText(3, _translate("MainWindow", "L <= C", None))
        self.comboBoxL.setItemText(4, _translate("MainWindow", "C1 < L < C2", None))
        self.comboBoxL.setItemText(5, _translate("MainWindow", "C1 < L <= C2", None))
        self.comboBoxL.setItemText(6, _translate("MainWindow", "C1 <= L < C2", None))
        self.comboBoxL.setItemText(7, _translate("MainWindow", "C1 <= L <= C2", None))
        self.comboBoxCos.setItemText(0, _translate("MainWindow", "Cos > C", None))
        self.comboBoxCos.setItemText(1, _translate("MainWindow", "Cos >= C", None))
        self.comboBoxCos.setItemText(2, _translate("MainWindow", "Cos < C", None))
        self.comboBoxCos.setItemText(3, _translate("MainWindow", "Cos <= C", None))
        self.comboBoxCos.setItemText(4, _translate("MainWindow", "C1 < Cos < C2", None))
        self.comboBoxCos.setItemText(5, _translate("MainWindow", "C1 < Cos <= C2", None))
        self.comboBoxCos.setItemText(6, _translate("MainWindow", "C1 <= Cos < C2", None))
        self.comboBoxCos.setItemText(7, _translate("MainWindow", "C1 <= Cos <= C2", None))
        self.comboBoxT.setItemText(0, _translate("MainWindow", "T > C", None))
        self.comboBoxT.setItemText(1, _translate("MainWindow", "T >= C", None))
        self.comboBoxT.setItemText(2, _translate("MainWindow", "T < C", None))
        self.comboBoxT.setItemText(3, _translate("MainWindow", "T <= C", None))
        self.comboBoxT.setItemText(4, _translate("MainWindow", "C1 < T < C2", None))
        self.comboBoxT.setItemText(5, _translate("MainWindow", "C1 < T <= C2", None))
        self.comboBoxT.setItemText(6, _translate("MainWindow", "C1 <= T < C2", None))
        self.comboBoxT.setItemText(7, _translate("MainWindow", "C1 <= T <= C2", None))
        self.comboBoxP.setItemText(0, _translate("MainWindow", "P > C", None))
        self.comboBoxP.setItemText(1, _translate("MainWindow", "P >= C", None))
        self.comboBoxP.setItemText(2, _translate("MainWindow", "P < C", None))
        self.comboBoxP.setItemText(3, _translate("MainWindow", "P <= C", None))
        self.comboBoxP.setItemText(4, _translate("MainWindow", "C1 < P < C2", None))
        self.comboBoxP.setItemText(5, _translate("MainWindow", "C1 < P <= C2", None))
        self.comboBoxP.setItemText(6, _translate("MainWindow", "C1 <= P < C2", None))
        self.comboBoxP.setItemText(7, _translate("MainWindow", "C1 <= P <= C2", None))
        self.nombreCantidadCarreteras_4.setText(_translate("MainWindow", "4. Resultados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabP2), _translate("MainWindow", "Programa 2", None))
        self.label_3.setText(_translate("MainWindow", "Programa 3", None))
        self.nombreOrdenEstructura.setText(_translate("MainWindow", "1. Digite el orden de la estructura (1-8):", None))
        self.nombreDatosEstructura.setText(_translate("MainWindow", "2. Introduzca los datos para la estructura y presione \"Evalúar Estructura\":", None))
        item = self.tableWidgetDatosEstructura.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "a", None))
        item = self.tableWidgetDatosEstructura.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "a", None))
        __sortingEnabled = self.tableWidgetDatosEstructura.isSortingEnabled()
        self.tableWidgetDatosEstructura.setSortingEnabled(False)
        self.tableWidgetDatosEstructura.setSortingEnabled(__sortingEnabled)
        self.pushButtonEvaluarEstructura.setText(_translate("MainWindow", "Evalúar Estructura", None))
        self.nombreCantidadCarreteras_5.setText(_translate("MainWindow", "4. Resultados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TapP3), _translate("MainWindow", "Programa 3", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "L > C", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "L >= C", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "L < C", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "L <= C", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "C1 < L < C2", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "C1 < L <= C2", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "C1 <= L < C2", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "C1 <= L <= C2", None))

